import * as THREE from 'three';
import { CONFIG } from './config.js';
import { ring } from './models.js';
export class Effects {
  constructor(scene,camera,settings){
    this.scene=scene;this.camera=camera;this.settings=settings;this.shake=0;this.particles=[];this.active=new Set();this.cursor=0;
    this.geometry=new THREE.IcosahedronGeometry(1,0);this.material=new THREE.MeshBasicMaterial({vertexColors:false,transparent:true,opacity:.85,depthWrite:false});
    this.mesh=new THREE.InstancedMesh(this.geometry,this.material,CONFIG.effects.high);this.mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.mesh.frustumCulled=false;scene.add(this.mesh);this.dummy=new THREE.Object3D();this.color=new THREE.Color();this.limit=CONFIG.effects.high;
    for(let i=0;i<CONFIG.effects.high;i++){this.particles.push({life:0});this.dummy.scale.setScalar(0);this.dummy.updateMatrix();this.mesh.setMatrixAt(i,this.dummy.matrix);this.mesh.setColorAt(i,this.color);}
    this.rings=Array.from({length:6},()=>{const m=ring(scene,0xffdf9c);m.material=m.material.clone();m.material.transparent=true;m.material.depthWrite=false;m.material.toneMapped=false;m.visible=false;return {mesh:m,life:0,max:.38};});
    this.arcs=Array.from({length:8},()=>{const positions=new Float32Array(21),coreVertices=new Float32Array(108),haloVertices=new Float32Array(108);const makeRibbon=(data,color,opacity)=>{const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(data,3).setUsage(THREE.DynamicDrawUsage));const line=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false,toneMapped:false,side:THREE.DoubleSide}));line.frustumCulled=false;line.visible=false;scene.add(line);return line;};return {line:makeRibbon(coreVertices,0xf3ffff,1),halo:makeRibbon(haloVertices,0x20bcef,.55),positions,coreVertices,haloVertices,life:0};});
    this.popups=Array.from({length:CONFIG.effects.popups},()=>{const element=document.createElement('span');element.className='score-popup';element.hidden=true;document.getElementById('popups').append(element);return {element,life:0};});
    this.project=new THREE.Vector3();
  }
  particle(x,y,z,color,life,size,vx,vy,vz){this.cursor=(this.cursor+1)%this.limit;const p=this.particles[this.cursor];p.x=x;p.y=y;p.z=z;p.vx=vx;p.vy=vy;p.vz=vz;p.life=life;p.max=life;p.size=size;p.color=color;this.active.add(this.cursor);this.mesh.setColorAt(this.cursor,this.color.setHex(color));}
  emit(x,y,z,color,count=8,life=.6,size=1){
    for(let i=0;i<count;i++)this.particle(x,y,z,color,life,(.05+Math.random()*.15)*size,(Math.random()-.5)*5,1+Math.random()*4,(Math.random()-.5)*5);this.mesh.instanceColor.needsUpdate=true;
  }
  setQuality(){this.limit=CONFIG.effects.high;this.mesh.count=this.limit;}
  shockwave(x,z,size,color=0xffdf9c){const r=this.rings.find(r=>r.life<=0)||this.rings[0];r.life=r.max;r.mesh.material.color.setHex(color);r.mesh.material.opacity=.8;r.mesh.position.set(x,.1,z);r.mesh.visible=true;r.size=size;this.shake=Math.max(this.shake,.1*size);}
  explosion(x,z,size=1){this.emit(x,.7,z,0xffffff,Math.round(7*size),.16,1.6);this.emit(x,.5,z,0xffaa68,Math.round(10*size),.42,1.25);this.emit(x,.2,z,0x8f9490,Math.round(7*size),.78,1.45);this.shockwave(x,z,size);}
  rocketTrail(x,y,z,angle){const sx=Math.sin(angle),sz=Math.cos(angle);this.particle(x-sx*.35,y,z-sz*.35,0x8d9694,.38,.19,-sx*.7,.45,-sz*.7);this.particle(x-sx*.2,y,z-sz*.2,0xffe4a0,.16,.12,-sx*1.6,.3,-sz*1.6);this.mesh.instanceColor.needsUpdate=true;}
  rocketExplosion(x,z,size=1){this.emit(x,.7,z,0xffffff,7,.14,1.8);this.emit(x,.55,z,0xff9d49,14,.38,1.55);this.emit(x,.25,z,0x697477,9,.65,1.35);this.shockwave(x,z,size,0xff9b50);}
  shotgunMuzzle(x,y,z,angle){const sx=Math.sin(angle),sz=Math.cos(angle),px=sz,pz=-sx;for(let i=0;i<7;i++){const d=.35+(i%3)*.37,spread=(i-3)*.11;this.particle(x+sx*d+px*spread,y,z+sz*d+pz*spread,i%2?0xffb94e:0xffffff,.17,.105+Math.abs(spread)*.15,sx*(3+i*.3)+px*spread*4,.4,sz*(3+i*.3)+pz*spread*4);}this.mesh.instanceColor.needsUpdate=true;}
  flameJet(x,z,angle,range){const sx=Math.sin(angle),sz=Math.cos(angle),px=sz,pz=-sx;for(let i=0;i<12;i++){const d=(range-.12)*(i+1)/13;if(d<=.05)break;const spread=(i%3-1)*Math.min(.48,d*.11),warm=i%3===0?0xfff5ad:i%3===1?0xffa344:0xf15d3c;this.particle(x+sx*d+px*spread,.58+(i%2)*.1,z+sz*d+pz*spread,warm,.21+i*.008,.17+d*.02,sx*(2+i*.15)+px*spread*.5,.65,sz*(2+i*.15)+pz*spread*.5);}this.mesh.instanceColor.needsUpdate=true;}
  electricBurst(x,z){this.particle(x,.9,z,0xffffff,.18,.23,0,1,0);for(let i=0;i<4;i++){const a=i*Math.PI/2+Math.random()*.5;this.particle(x,.8,z,0x60eaff,.24,.11,Math.sin(a)*3,1.4,Math.cos(a)*3);}this.mesh.instanceColor.needsUpdate=true;}
  arc(ax,az,bx,bz){const arc=this.arcs.find(a=>a.life<=0)||this.arcs[0],p=arc.positions,dx=bx-ax,dz=bz-az,length=Math.max(.1,Math.hypot(dx,dz)),perpX=-dz/length,perpZ=dx/length;for(let i=0;i<7;i++){const t=i/6,j=i===0||i===6?0:(Math.random()-.5)*Math.min(1.1,length*.22),k=i*3;p[k]=ax+dx*t+perpX*j;p[k+1]=.93+Math.sin(t*Math.PI)*.3+(i%2)*.08;p[k+2]=az+dz*t+perpZ*j;}this.arcRibbon(p,arc.haloVertices,.17);this.arcRibbon(p,arc.coreVertices,.055);arc.line.geometry.attributes.position.needsUpdate=true;arc.halo.geometry.attributes.position.needsUpdate=true;arc.line.material.opacity=1;arc.halo.material.opacity=.55;arc.line.visible=arc.halo.visible=true;arc.life=.2;}
  arcRibbon(path,out,width){for(let i=0;i<6;i++){const a=i*3,b=a+3,o=i*18,dx=path[b]-path[a],dz=path[b+2]-path[a+2],length=Math.max(.001,Math.hypot(dx,dz)),nx=-dz/length*width,nz=dx/length*width;out.set([path[a]+nx,path[a+1],path[a+2]+nz,path[a]-nx,path[a+1],path[a+2]-nz,path[b]+nx,path[b+1],path[b+2]+nz,path[b]+nx,path[b+1],path[b+2]+nz,path[a]-nx,path[a+1],path[a+2]-nz,path[b]-nx,path[b+1],path[b+2]-nz],o);}}
  popup(x,z,text,color='#fff9d5'){const p=this.popups.find(p=>p.life<=0)||this.popups[0];Object.assign(p,{x,z,life:1.2});p.element.textContent=text;p.element.style.color=color;p.element.hidden=false;}
  update(dt){this.shake=Math.max(0,this.shake-dt);let changed=false;for(const i of this.active){const p=this.particles[i];p.life=Math.max(0,p.life-dt);if(p.life>0){p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.vy-=6*dt;this.dummy.position.set(p.x,Math.max(.07,p.y),p.z);this.dummy.rotation.set(0,0,0);this.dummy.scale.setScalar(p.size*Math.min(1,p.life*4));}else{this.dummy.scale.setScalar(0);this.active.delete(i);}this.dummy.updateMatrix();this.mesh.setMatrixAt(i,this.dummy.matrix);changed=true;}if(changed)this.mesh.instanceMatrix.needsUpdate=true;
    for(const r of this.rings)if(r.life>0){r.life=Math.max(0,r.life-dt);r.mesh.visible=r.life>0;r.mesh.scale.setScalar((r.max-r.life)*8*r.size);r.mesh.material.opacity=.8*r.life/r.max;}
    for(const a of this.arcs)if(a.life>0){a.life=Math.max(0,a.life-dt);a.line.visible=a.halo.visible=a.life>0;a.line.material.opacity=a.life/.2;a.halo.material.opacity=.55*a.life/.2;}
    for(const p of this.popups)if(p.life>0){p.life-=dt;p.element.hidden=p.life<=0;}
  }
  render(){for(const p of this.popups)if(p.life>0){this.project.set(p.x,2+(1.2-p.life),p.z).project(this.camera);p.element.style.transform=`translate(${(this.project.x*.5+.5)*innerWidth}px,${(-this.project.y*.5+.5)*innerHeight}px) translate(-50%,-50%)`;p.element.style.opacity=Math.min(1,p.life*3);}}
  clear(){for(const i of this.active){const p=this.particles[i];p.life=0;this.dummy.scale.setScalar(0);this.dummy.updateMatrix();this.mesh.setMatrixAt(i,this.dummy.matrix);}this.active.clear();this.mesh.instanceMatrix.needsUpdate=true;for(const p of this.popups){p.life=0;p.element.hidden=true;}for(const r of this.rings){r.life=0;r.mesh.visible=false;}for(const a of this.arcs){a.life=0;a.line.visible=a.halo.visible=false;}this.shake=0;}
}
