import * as THREE from 'three';
import { CONFIG } from './config.js';
import { clamp, readStorage, writeStorage } from './core.js';
import { material, tankModel } from './models.js';
import { Input } from './input.js';
import { World } from './world.js';
import { Player } from './player.js';
import { Enemies } from './enemies.js';
import { Combat } from './combat.js';
import { Effects } from './effects.js';
import { Audio } from './audio.js';
import { UI } from './ui.js';

export class Game {
  constructor(){
    this.state='menu';this.touchDevice=matchMedia('(pointer: coarse)').matches||navigator.maxTouchPoints>0;this.settings={mute:false,volume:.6,shake:true,quality:'high'};
    const stored=readStorage('chibi-best',0);this.best=Number.isFinite(stored)?Math.max(0,Math.floor(stored)):0;this.material=material;
    this.renderer=new THREE.WebGLRenderer({canvas:document.getElementById('game'),antialias:false,alpha:false,powerPreference:'high-performance'});const gl=this.renderer.getContext(),debugInfo=gl.getExtension('WEBGL_debug_renderer_info'),gpuName=`${debugInfo?gl.getParameter(debugInfo.UNMASKED_RENDERER_WEBGL):''} ${gl.getParameter(gl.RENDERER)||''}`;this.softwareRenderer=/swiftshader|software|llvmpipe|microsoft basic/i.test(gpuName);this.renderer.setClearColor(0xe5ecdb);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=this.softwareRenderer?THREE.NoToneMapping:THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.2;
    this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0xe5ecdb);this.scene.fog=new THREE.Fog(0xe5ecdb,75,145);this.daySky=new THREE.Color(0xe5ecdb);this.nightSky=new THREE.Color(0x243844);this.dayHemi=new THREE.Color(0xfff6dd);this.nightHemi=new THREE.Color(0x7792bd);this.daySun=new THREE.Color(0xfff0da);this.nightSun=new THREE.Color(0x9db9dc);
    this.camera=new THREE.OrthographicCamera(-24,24,18,-18,.1,180);this.focus=new THREE.Vector3();this.cameraTarget=new THREE.Vector3();this.labelPosition=new THREE.Vector3();this.cameraOffset=new THREE.Vector3(38,48,38);this.camera.position.copy(this.cameraOffset);this.camera.lookAt(this.focus);
    this.hemi=new THREE.HemisphereLight(0xfff6dd,0x91b3a0,2.6);this.scene.add(this.hemi);this.sun=new THREE.DirectionalLight(0xfff0da,3.2);this.sun.position.set(-20,40,20);this.sun.castShadow=false;this.scene.add(this.sun);
    this.audio=new Audio(this.settings);const unlockAudio=e=>{if(e.target?.closest?.('#play'))this.audio.setScene('playing');this.audio.unlock();window.removeEventListener('pointerdown',unlockAudio);window.removeEventListener('keydown',unlockAudio);};window.addEventListener('pointerdown',unlockAudio);window.addEventListener('keydown',unlockAudio);this.input=new Input(this.renderer.domElement,force=>this.togglePause(force),()=>{if(this.state==='over')this.start();});
    this.effects=new Effects(this.scene,this.camera,this.settings);this.world=null;this.enemies=new Enemies(this);this.combat=new Combat(this);this.reset(1709);this.ui=new UI(this);this.previewTanks=[];this.makePreview();this.setQuality();this.resize();
    window.addEventListener('resize',()=>this.resize());document.addEventListener('visibilitychange',()=>{if(document.hidden){if(this.audio.context)this.audio.context.suspend().catch(()=>{});}else if(this.audio.context)this.audio.unlock();});this.accumulator=0;this.last=performance.now();this.renderLast=0;this.uiAccumulator=0;this.frameCount=0;
    this.renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();this.togglePause(true);document.getElementById('error').hidden=false;document.getElementById('error-message').textContent='WebGL đã mất kết nối. Tải lại trang để khởi động lại.';});
    document.getElementById('loading').hidden=true;this.frame=this.frame.bind(this);this.frameId=requestAnimationFrame(this.frame);
  }
  makePreview(){for(const [x,z,color,type] of [[12,0,0xe8836d,'scout'],[0,-12,0xe2ae59,'mortar'],[-12,12,0xb68abf,'heavy']]){const m=tankModel(color,type);m.root.position.set(x,0,z);m.turret.rotation.y=Math.PI*.7;m.body.rotation.y=Math.PI*.65;this.scene.add(m.root);this.previewTanks.push(m);}this.player.aim=-1.1;this.player.angle=-.6;this.player.sync(0);}
  removePreview(){for(const m of this.previewTanks)m.root.removeFromParent();this.previewTanks=[];}
  reset(seed){this.input.clear();this.enemies.clear();this.combat.clear();this.effects.clear();this.player?.dispose();this.world?.dispose();this.world=new World(this.scene,seed);this.player=new Player(this.scene);this.time=0;this.score=0;this.kills=0;this.combo=0;this.maxCombo=1;this.comboTime=0;this.newBest=false;this.milestones=new Set();this.enemies.spawnTimer=3;this.enemies.eliteTimer=CONFIG.director.eliteEvery;this.enemies.assaultTimer=CONFIG.director.assaultFirst;this.enemies.assaultRemaining=0;this.enemies.serial=0;this.accumulator=0;this.uiAccumulator=0;this.focus.set(0,0,0);this.setNight(false,true,true);this.ui?.clear();}
  start(){this.audio.setScene('playing');this.audio.unlock();this.removePreview();const seed=new URLSearchParams(location.search).get('seed');this.reset(seed!==null?Number(seed)>>>0:crypto.getRandomValues(new Uint32Array(1))[0]);this.state='playing';this.ui.show(this.state);this.last=performance.now();this.resize();this.ui.toast(this.input.touchCapable?'Kéo trái để đi · Kéo phải để ngắm và bắn':'Giữ chuột để bắn · Space để lướt né');document.activeElement?.blur();}
  home(){this.input.clear();this.removePreview();this.reset(1709);this.state='menu';this.audio.setScene('menu');this.makePreview();this.ui.show('menu');this.resize();}
  togglePause(force=false){if(force&&this.state!=='playing')return;if(this.state==='over'||this.state==='menu')return;this.state=this.state==='playing'?'paused':'playing';this.audio.setScene(this.state);this.input.clear();this.accumulator=0;this.last=performance.now();this.ui.show(this.state);if(this.state==='playing'){this.audio.unlock();document.activeElement?.blur();}}
  end(){if(this.state!=='playing')return;this.state='over';this.input.clear();this.effects.explosion(this.player.x,this.player.z,2);this.audio.play('explosion');this.audio.setScene('over');const score=Math.floor(this.score);this.newBest=score>this.best;this.best=Math.max(this.best,score);writeStorage('chibi-best',this.best);this.ui.show('over');}
  onKill(e){this.combo=this.comboTime>0?Math.min(CONFIG.combat.maxCombo,this.combo+1):1;this.comboTime=CONFIG.combat.comboWindow;this.maxCombo=Math.max(this.maxCombo,this.combo);const points=e.points*this.combo;this.score+=points;this.kills++;this.effects.popup(e.x,e.z,`+${points}${this.combo>1?' ×'+this.combo:''}`);}
  step(dt){if(this.state!=='playing')return;const before=this.time;this.time+=dt;this.score+=CONFIG.combat.survivalScore*dt;this.comboTime-=dt;if(this.comboTime<=0)this.combo=0;this.player.update(dt,this);this.enemies.update(dt);this.combat.update(dt);this.effects.update(dt);for(const milestone of [30,60,120])if(before<milestone&&this.time>=milestone&&!this.milestones.has(milestone)){this.milestones.add(milestone);this.score+=milestone*2;this.ui.toast(`SỐNG SÓT ${milestone} GIÂY · +${milestone*2} ĐIỂM`);this.audio.play('pickup');}const night=Math.floor(this.time/CONFIG.world.phaseDuration)%2===1;if(night!==this.isNight)this.setNight(night);this.uiAccumulator+=dt;if(this.uiAccumulator>=1/CONFIG.performance.uiFPS){this.ui.update(this.uiAccumulator);this.uiAccumulator=0;}}
  setNight(night,silent=false,instant=false){const changed=this.isNight!==night;this.isNight=night;document.body.classList.toggle('night',night);this.enemies.setNight(night);if(changed&&!silent&&this.ui){this.ui.toast(night?'ĐÊM XUỐNG · XE TĂNG ZOMBIE ×2 MÁU':'BÌNH MINH · XE TĂNG TRỞ LẠI BÌNH THƯỜNG');this.audio.play('warning');}this.updateDayLighting(99);this.world.updateGroundEffects(this.player,this.enemies.list,night);}
  updateDayLighting(dt){const targetSky=this.isNight?this.nightSky:this.daySky,targetHemi=this.isNight?this.nightHemi:this.dayHemi,targetSun=this.isNight?this.nightSun:this.daySun,f=dt>10?1:1-Math.exp(-dt*1.15);this.scene.background.lerp(targetSky,f);this.scene.fog.color.copy(this.scene.background);this.hemi.color.lerp(targetHemi,f);this.sun.color.lerp(targetSun,f);this.hemi.intensity+=((this.isNight?1.15:2.6)-this.hemi.intensity)*f;this.sun.intensity+=((this.isNight?1.25:3.2)-this.sun.intensity)*f;this.renderer.toneMappingExposure+=((this.isNight?0.82:1.2)-this.renderer.toneMappingExposure)*f;}
  updateCamera(dt){const menu=this.state==='menu';this.cameraTarget.set(menu?-6:clamp(this.player.x,-17,17),0,menu?6:clamp(this.player.z,-17,17));this.focus.lerp(this.cameraTarget,1-Math.exp(-dt*5));this.camera.position.copy(this.focus).add(this.cameraOffset);if(this.settings.shake&&this.state==='playing'&&this.effects.shake>0){const n=this.effects.shake;this.camera.position.x+=(Math.random()-.5)*n;this.camera.position.z+=(Math.random()-.5)*n;}this.camera.lookAt(this.focus);if(menu){this.camera.setViewOffset(innerWidth,innerHeight,-innerWidth*.17,0,innerWidth,innerHeight);}else this.camera.clearViewOffset();this.camera.updateMatrixWorld();if(menu){this.labelPosition.set(this.player.x,2,this.player.z).project(this.camera);const label=document.querySelector('.field-label');label.style.left=`${(this.labelPosition.x*.5+.5)*innerWidth+15}px`;label.style.top=`${(-this.labelPosition.y*.5+.5)*innerHeight-130}px`;}}
  frame(now){this.frameId=requestAnimationFrame(this.frame);if(document.hidden){this.last=this.renderLast=now;return;}const playFPS=this.softwareRenderer?CONFIG.performance.softwareFPS:CONFIG.performance.highFPS,fps=this.state==='playing'?playFPS:CONFIG.performance.idleFPS,interval=1000/fps;if(now-this.renderLast<interval)return;this.renderLast=now-(now-this.renderLast)%interval;const dt=Math.min(.1,Math.max(0,(now-this.last)/1000));this.last=now;if(this.state==='playing'){this.accumulator+=dt;while(this.accumulator>=CONFIG.step){this.step(CONFIG.step);this.accumulator-=CONFIG.step;if(this.state!=='playing'){this.accumulator=0;break;}}}this.updateCamera(dt);this.world.fadeOccluders(this.player);this.world.updateGroundEffects(this.player,this.enemies.list,this.isNight);this.effects.render();this.renderer.render(this.scene,this.camera);this.frameCount++;}
  resize(){const aspect=innerWidth/innerHeight,menu=this.state==='menu',height=menu?40:this.touchDevice&&aspect>1?22:32;this.camera.left=-height*aspect/2;this.camera.right=height*aspect/2;this.camera.top=height/2;this.camera.bottom=-height/2;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight);this.updateCamera(1);}
  setQuality(){this.settings.quality='high';this.renderScale=this.softwareRenderer?1:1.25;this.renderer.setPixelRatio(Math.min(devicePixelRatio,this.renderScale));this.renderer.shadowMap.enabled=false;this.sun.castShadow=false;this.effects.setQuality();this.renderLast=0;this.resize();}
}
try{const game=new Game();if(new URLSearchParams(location.search).has('debug'))window.__game=game;}catch(error){console.error(error);document.getElementById('loading').hidden=true;document.getElementById('error').hidden=false;document.getElementById('error-message').textContent=error.message;}
